default_roles:
  #- system
  - auto-cpufreq
  - alacritty
  
  #todo- bash
  
  - btop
  - discord
  #- docker
  #- flatpak
  - fonts
  - fzf
  
  #- gh
  - git
  #- gnome-postinstall
  - gnome-wallpaper
  - gnome-apps
  
  
  - lazygit
  - lsd
  
  - nala
  - naps2
  - ncdu
  - obsidian
  - onlyoffice
  - pacseek
  - pika-backup
  - python
  - signal-desktop
  - speedtest-cli
  - spotify
  - ssh
  - sshfs
  #- starship
  - syncthing
  - tailscale
  #- taskfile
  - teamviewer
  #- terraform
  #- terragrunt
  - tldr
  - vlc
  - vs-code
  - zellij
  - zoxide
  - zsh

#git_user_name: "blackbunt"
#op:
#  git:
#    user:
#      email: "op://Personal/GitHub/email"
#    allowed_signers: "op://Personal/TechDufus SSH/allowed_signers"
#  ssh:
#    github:
#      techdufus:
#        - name: id_ed25519
#          vault_path: "op://Personal/TechDufus SSH"
#        - name: raft-infra
#          vault_path: "op://Raft/Raft-SSH"
# FIXME: See `system/tasks/main.yml` for how to structure this var looping.
  # system:
  #   hosts:
  #     - item: op://Raft/rdp-demo-local-ingress/notesPlain
  #       account: my.1password.com

#k8s:
#  repo:
#    version: "v1.26"

#helm:
#  repos:
#    - name: traefik
#      url: https://helm.traefik.io/traefik

#go:
#  packages:
#    - package: github.com/go-task/task/v3/cmd/task@latest
#      cmd: task
#    - package: github.com/gcla/termshark/v2/cmd/termshark@v2.4.0
#      cmd: termshark
    # - package: github.com/stillmatic/chat@latest
    #   cmd: chat
