---
- name: "gnome-apps | ArchLinux | Install GNOME applications"
  community.general.pacman:
    name:
      - gnome-firmware
      - gnome-maps
      - gnome-mines
      - gnome-music
      - gnome-photos
      - gnome-calendar
      - gnome-contacts
      - railway
      - geary
    state: present
    update_cache: true
  become: true
